[package]
name = "metamask-sdk"
authors = [ "Willem Olding <willemolding@gmail.com>" ]
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
js-sys = "0.3.64"
serde-wasm-bindgen = "0.5.0"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
